{% set version = '0.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstudioapi
  version: {{ version|replace("-", "_") }}

source:
  fn: rstudioapi_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rstudioapi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstudioapi/rstudioapi_{{ version }}.tar.gz
  sha256: a541bc76ef082d2c27e42fd683f8262cb195b1497af3509178d2642870397a8c

build:
  merge_build_host: True  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('rstudioapi')"           # [not win]
    - "\"%R%\" -e \"library('rstudioapi')\""  # [win]

about:
  home: https://github.com/rstudio/rstudioapi
  license: MIT
  summary: Access the RStudio API (if available) and provide informative error messages when
    it's not.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - croth1
    - dbast
