travis:
  secure:
    BINSTAR_TOKEN: nd3BYju1gcQjrCXuSPMEy+YrGmKblXfZA4+9eWfF8h+ihkX895kcmnMuV+YuEWU7nnhWB87xQrY2qSPcbJvv2O4b2xY+MxK7TZV33vF+RCd56rqlT8V/VMB6DjH3w7o2M/67rXcHIEVJV7kgryi3zx59tWjuqGMrLEsvv4JumbAATP/N/gUZ8LPJG0U/bCh4U/sUkw6nFUKTM/Q6HWCLvSRz9wWmPgb0kZrRZ078OxRyFqFR2oR3IhRA5lOQ6iIr2AzFvifoEt0j/qCIU0QAgKzm7076E9diUUpld1yTGSynVXLpRb/6sfc4DbvDs49OqDVoGNRW7b3+kiNiw4l/RG20REuhxgM+wVssr13Sz0bblcDLxsRLtAKJ2Q+ecEpGYdPOFvyCj3+0vbk0GVPMjllWi8qB6vEu5r5bvJsBqbOK6V1YJMJMYaE1w2Y43yFPTAcPBJogYukbxvJBuzJK3DvOv56r24buqQr5i6ysEh3c/dm7xm/0gtjJ5grG6a49cUxnk2PP7mMAGYvpEa8f8nPzJa/qya5+aj5q1yUEqDDuqOVzxHiEADBx99nfra8Mj8ssbczcCeEDJcUBmrxybR9kj8P7ceTFHQkIoUogJnO211wjPkhL0Wdx9WkDou9Y7Teq2e6ujtOVjW5kncVv3Fo/z3/3PNnSE1qnHCyzVOk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
