appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EUp4mHC/BFWG1SJCyUgYVtC8SB5wC1pGhduXHWeoLgQGa5UOJsgqc5J50Za2rdJxbt3JrYNmt/LLihSTQeXiXcwmlW5OWBXjClWgMzesFytpbi2fx8SKkF9zMPkU5dPcIwhhbIvX9x7gIa6Nh0fuj2hV2gr6wFssAEzKPUM67iR6HzI0lRf8kLBinMjZoiZGk/gHNMfvMNm0G5yzF3aK9P5KGBVYvCJfq8laDGK4VIjZvLpnn/CP9pHoRLQ5MChkD1swfM/BRJ6uJztQSo+gzjHDssiGsVS1nih6I4aqNVRLyKtKXZKJea8HwCeYTmGTKdci0jo4sQLtUlMUCpN5gugOFCgu/jLM8tZBpp+g2Qe4vFCl5ZQoIVwkhDUdYumNcwu56nEUnkJOw/V86OlIsgMqGnNBFUmnEePSPDWAyE7O1F4MlnAOnzXusFGSB+JQSZYKWL+LjnTa6g/xPNU0bBWHbbXAAMqRS6zlyvHoKLP1jsrEkV3wyBIMvofCnHr5yD+pGeSIhasCxQY6oGqqKG5PPVEHZoMQ99k49BSA0SbAv6nuzR+/U+viwVZ9ki8EMIzORE+n5F7bLPNPUqnGEQAfXOSN7vK27q9Vgl445q4IR9OFDZCZO45Uh5IVYgW1hOFx7FWvEtyJl6wC3RYpMWWtOUTJXbweamU7N9A6yLk=
conda_forge_output_validation: false
