travis:
  secure:
    BINSTAR_TOKEN: XQiJmTTrHT9faLf2Kn4WL0GjtQHBmyZXDkZpbPw8lxEsSnPwPJ5aM3b91wzO1Vv3WDIvJ+da6tioh0jl+Jkocpi7A1egUJ8usphPOI/8QB4cc3Qv7gflfQICU1JOKDLk9lZgGEfgAD460Ty27wmaCSmSm0aB+wQ8MieABty98tMm9IfglLkgR2V2b7ydG0P/9H7l4/tYvHipBxwKiyqSIbHNJWMgqBAimdf7ekpKG3qpVjWQahmNNDLLLYxNSwRqhFBupuK5APl6od0Ua6oQ6q+ekv0Eg5fEmL+Yj8aFwD3DuLhHtPcDQCbF9/v+yIozWCp/ro2eKhTovVke/mXYlvhEKXjTxr4yGaLcZQvk4gGIWbvF3vrxZcxwST9910FjJREe1pI6Iat6+8rLA7P5/N9PPUSlCt4+Wkesiy2QUWupBe3RnIjfM0j6DpVodEg7SG8MEgQsNPUWZGrmfS8YEqIyvwDa2A5smcmKsoeJf+U4ZcaY46Ogb1RP3dWWWBA972mL+27wtKrvPSGqWsrZ4KQE6b0q5DB00ev36UFUneawOLD6xbz5inNVXhTOFtK9c81DnvjU1Kw/sNxsQY1TZT4Y+HdOxTKxs4fPyfW/U50UJxZnxSKkvozhnZ71aflJLwSk0++crzpmy4coYhmJI2NjivtJM6a3XL/yldeY80E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
